#pragma once

#define ENGINE_DLL					"engine.dll"
#define CLIENT_DLL					"client.dll"
#define VSTD_DLL					"vstdlib.dll"
#define VGUI_DLL					"vgui2.dll"
#define VGUIMAT_DLL					"vguimatsurface.dll"
#define MATERIAL_DLL				"materialsystem.dll"
#define LOCALIZE_DLL				"localize.dll"
#define STUDIORENDER_DLL			"studiorender.dll"
#define INPUTSYSTEM_DLL				"inputsystem.dll"
#define SHARED_API					"shaderapidx9.dll"
#define TIER_DLL					"tier0.dll"
#define PANORAMA_DLL				"panorama.dll"
#define FILESYS_DLL					"filesystem_stdio.dll"
#define DATACACHE_DLL				"datacache.dll"
#define SERVER_DLL					"server.dll"