#pragma once

enum VTableIndexes
{
	ISPLAYER = 158,
	ISWEAPON = 166,
	INACCURACY = 483,
	SPREAD = 453,
	WEAPONINFO = 461,
	PUNCH = 346,
	ABS_ORIGIN = 10,
	ABS_ANGLE = 11,
	CLIENT_CLASS = 2,
	COLLIDEABLE = 3,
	GET_INDEX = 10,
	RENDER_BOUNDS = 17,
	SETUP_BONES = 13,
	GET_MODEL = 8,
	DRAW_MODEL = 9,
	IS_DORMANT = 9,
	RENDERABLE_TO_WORLD = 32,
	RELEASE = 1,
	PRE_DATA_CHANGED = 4,
	DATA_CHANGED = 5,
	PRE_DATA_UPDATE = 6,
	POST_DATA_UPDATE = 7,
};