#include "drawing.hpp"
#include "../GUI/Controls/Tab/Tab.hpp"
#include "../../globals.hpp"
#include "../../../SDK/interfaces/interfaces.hpp"

#define CA const auto

void GUI::initGui()
{
	menu = new Menu(VK_INSERT);
	//fatchad = new TextureHolder(IMAGE_PNG1);

	CA legitbot = menu->addTab("aimbot");
	CA visuals = menu->addTab("visuals");
	CA visuals3 = menu->addTab("visuals3");
	CA visuals4 = menu->addTab("visuals4");

	CA legitbot1 = legitbot->addGroup("legitbot1");
	legitbot1->addCheckBox("title", &testBool);
	legitbot1->addKeyHolder(&key);
	//legitbot1->addComboBox("title", m_vec, &selected);
	legitbot1->addColorPicker(&colorD);
	legitbot1->addCheckBox("title", &testBool);
	legitbot1->addHelpMarker("this is some helper, draw small text here");
	legitbot1->addCheckBox("title", &testBool);
	legitbot1->addCheckBox("title", &testBool);
	legitbot1->addButton("button",
		[]()
		{
			interfaces::console->consoleColorPrintf(Colors::Green, "this is generated by button click\n");
		});
	legitbot1->addCheckBox("title", &testBool);
	//legitbot1->addKeyHolder("keyhold", &key);
	legitbot1->addSlider("dawdwad", { 10.0f, 80.0f }, &floating);
	legitbot1->addCheckBox("title", &testBool);
	legitbot1->addTextInput("sssss", &text);

	CA legitbot2 = legitbot->addGroup("legitbot2", Lining::PAD);
	legitbot2->addCheckBox("title", &testBool);
	legitbot2->addCheckBox("title", &testBool);
	legitbot2->addComboBox("titlefdWda", m_vec, &selected2);
	legitbot2->addMultiBox("titledddddd", m_vec, &m_vec2);
	legitbot2->addCheckBox("title", &testBool);
	legitbot2->addCheckBox("title", &testBool);

	CA legitbot3 = legitbot->addGroup("legitbot2", Lining::PAD);
	legitbot3->addCheckBox("title", &testBool);
	legitbot3->addCheckBox("title", &testBool);
	legitbot3->addMultiBox("title2", m_vec, &m_vec2);
	legitbot3->addComboBox("title2", m_vec, &selected);
	legitbot3->addCheckBox("title", &testBool);
	legitbot3->addCheckBox("title", &testBool);

	CA visuals1 = visuals->addGroup("yo");
	visuals1->addCheckBox("title", &testBool);
	visuals1->addCheckBox("title", &testBool);
	visuals1->addCheckBox("title", &testBool);
	visuals1->addCheckBox("title", &testBool);
	visuals1->addCheckBox("title", &testBool);
	visuals1->addCheckBox("title", &testBool);

	CA visuals31 = visuals3->addGroup("yo2");
	visuals31->addCheckBox("title", &testBool);
	visuals31->addCheckBox("title", &testBool);
	visuals31->addCheckBox("title", &testBool);
	visuals31->addCheckBox("title", &testBool);
	visuals31->addCheckBox("title", &testBool);
	visuals31->addCheckBox("title", &testBool);

	CA visuals32 = visuals4->addGroup("yo3");
	visuals32->addCheckBox("title", &testBool);
	visuals32->addCheckBox("title", &testBool);
	visuals32->addCheckBox("title", &testBool);
	visuals32->addCheckBox("title", &testBool);
	visuals32->addCheckBox("title", &testBool);
	visuals32->addCheckBox("title", &testBool);

	LOG(LOG_INFO, "init menu success");
}

void GUI::draw()
{
	menu->draw();

	//fatchad->draw(400, 500);
}