#pragma once

#define MENU_START_X 600
#define MENU_START_Y 400

#define MENU_WIDTH 800
#define MENU_HEIGHT 400

#define TAB_HEIGHT 20

#define CHECKBOX_WIDTH 10
#define CHECKBOX_HEIGHT 10

#define BUTTON_WIDTH 50
#define BUTTON_HEIGHT 20

#define COMBOBOX_WIDTH 150
#define COMBOBOX_HEIGHT 20

#define MULTIBOX_WIDTH 150
#define MULTIBOX_HEIGHT 20

#define TEXTINPUT_WIDTH 150
#define TEXTINPUT_HEIGHT 20

#define KEYHOLDER_WIDTH 5
#define KEYHOLDER_HEIGHT 8

#define SILDER_WIDTH 150
#define SLIDER_HEIGHT 7

#define COLORPICKER_WIDTH 150
#define COLORPICKER_HEIGHT 150

#define GROUPX_PAD 180
#define GROUPY_PAD 20