#pragma once

// should just use it for all boxes
#define BOX_WIDTH 130

#define MENU_START_X 600
#define MENU_START_Y 400

#define MENU_WIDTH 800
#define MENU_HEIGHT 400

#define TAB_HEIGHT 20

#define CHECKBOX_WIDTH 10
#define CHECKBOX_HEIGHT 10

#define BUTTON_WIDTH BOX_WIDTH
#define BUTTON_HEIGHT 20

#define COMBOBOX_WIDTH BOX_WIDTH
#define COMBOBOX_HEIGHT 20

#define MULTIBOX_WIDTH BOX_WIDTH
#define MULTIBOX_HEIGHT 20

#define TEXTINPUT_WIDTH BOX_WIDTH
#define TEXTINPUT_HEIGHT 20

#define KEYHOLDER_WIDTH 5
#define KEYHOLDER_HEIGHT 8

#define SILDER_WIDTH BOX_WIDTH
#define SLIDER_HEIGHT 7

#define COLORPICKER_WIDTH 150
#define COLORPICKER_HEIGHT 150

#define GROUPX_PAD 200
#define GROUPY_PAD 20

#define PAD_TEXT_X 20